# Generated by Django 4.1.13 on 2024-10-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VolunteerApp', '0002_remove_task_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='hours_reward',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='total_hours',
            field=models.IntegerField(default=0),
        ),
    ]
