# Generated by Django 4.1.13 on 2024-10-30 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('VolunteerApp', '0003_alter_task_hours_reward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='current_participants',
            field=models.ManyToManyField(blank=True, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='task',
            name='max_participants',
            field=models.IntegerField(default=1),
        ),
    ]
